### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by Meghadri-Koley** [SamarthTech/Samarth-Website#100] opened 2022-12-20 07:17 UTC
**Add a form validation so that if the required inputs are blank then the button animation will not work**
![image](https://user-images.githubusercontent.com/77243269/208605876-e24013b1-6817-402f-8ad0-7370f27afcd9.png)

**Comment by syed-muheed** [comment] 2023-09-27 16:51
Kindly assign this to me

**Comment by ZainabR11** [comment] 2023-09-27 21:37
I'm confident in implementing form validation effectively. Please entrust me with this task!

**Comment by aman1205** [comment] 2023-10-01 05:37
I want  to work on this task ,beaccuse recently work with same issue

**Comment by SamarthTech** [comment] 2023-10-01 06:53
Assigned

**Comment by aman1205** [comment] 2023-10-01 09:26
Give url where the problem is occur  beacause  did't find that .

**Closed** 2023-10-01 12:23 UTC
Labels: enhancement

**Comment by ZainabR11** [comment] 2023-10-06 19:36
I have pulled request for improved footer section #110. Kindly consider. Zainab Rizwan-------- Original message --------From: Samarth - Tech ***@***.***>Date: Sun, 1 Oct 2023, 11:53 amTo: SamarthTech/Samarth-Website ***@***.***>Cc: ZainabR11 ***@***.***>, Assign ***@***.***>Subject: Re: [SamarthTech/Samarth-Website] Form Validation (Issue #100)
Assigned
